Added "make test-pqfo/hksu"

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,23 +7,19 @@ orbs:
 
 workflows:
   version: 2
-  linux:
+  macos:
     jobs:
       - test:
           filters:
             branches:
               only:
                 - master
+                - tmp
 
 jobs:
   test:
 
-    machine: {image: ubuntu-2004:202010-01}
-
-#    environment:
-#      # Customize the JVM maximum heap limit
-#      JVM_OPTS: -Xmx3200m
-#      TERM: dumb
+    macos: {xcode: 11.6.0}
 
     steps:
       - checkout
@@ -32,34 +28,34 @@ jobs:
           command: |
             git submodule update --init --recursive
 
-
       # Download and cache Isabelle
       - restore_cache:
           keys:
-            - v2-isabelle-2019-linux
+            - v2-isabelle-2019-macos
       - run:
           name: Downloading Isabelle 2019 (if needed)
           shell: bash
           command: |
             if ! [ -e "$HOME/install/Isabelle2019" ]; then
               mkdir -p ~/install
-              case linux in
+              case macos in
                 windows)
                   curl "https://isabelle.in.tum.de/website-Isabelle2019/dist/Isabelle2019.exe" -o /tmp/isabelle.exe
                   7z x -y -o"$HOME/install" /tmp/isabelle.exe;;
-                linux)
-                  curl https://isabelle.in.tum.de/website-Isabelle2019/dist/Isabelle2019_linux.tar.gz | tar -x -z -C ~/install;;
+                linux|macos)
+                  curl https://isabelle.in.tum.de/website-Isabelle2019/dist/Isabelle2019_macos.tar.gz | tar -x -z -C ~/install;;
                 *) false;;
               esac
             fi
       - save_cache:
           paths:
-            - ~/install/Isabelle2019
-          key: v2-isabelle-2019-linux
+            - ~/install/Isabelle2019.app/Isabelle
+          key: v2-isabelle-2019-macos
 
       # Download and cache AFP
       - restore_cache:
           keys:
+            - v3-afp-2019
             - v2-afp-2019
       - run:
           name: Downloading AFP 2019
@@ -68,50 +64,16 @@ jobs:
             if ! [ -e ~/install/afp-2019 ]; then
               mkdir -p ~/install/afp-2019
               case 2019 in
-                2019) curl https://master.dl.sourceforge.net/project/afp/afp-Isabelle2019/afp-2019-08-19.tar.gz | tar -x -z -C ~/install/afp-2019 --strip 1;;
+                2019)
+                  curl https://master.dl.sourceforge.net/project/afp/afp-Isabelle2019/afp-2019-08-19.tar.gz -o /tmp/afp.tar.gz
+                  tar -x -z -f /tmp/afp.tar.gz -C ~/install/afp-2019 --strip 1;;
                 *) false;;
               esac
             fi
       - save_cache:
           paths:
             - ~/install/afp-2019
-          key: v2-afp-2019
-
-#      - restore_cache:
-#          keys:
-#            - v1-isabelle-heaps-2019-linux-Analysis
-#            - v1-isabelle-heaps-2019-linux-
-#      - run:
-#          name: Building HOL-Analysis
-#          shell: bash
-#          command: |
-#            if ! compgen -G ~/".isabelle/Isabelle2019/heaps/*/HOL-Analysis"; then
-#              ~/install/Isabelle2019/bin/isabelle build -v -b -d ~/install/afp-2019/thys HOL-Analysis
-#            fi
-#      - save_cache:
-#          paths:
-#            - ~/.isabelle
-#          key: v1-isabelle-heaps-2019-linux-Analysis
-
-
-#      - restore_cache:
-#          keys:
-#            - v1-isabelle-heaps-2019-linux-Prerequisites-{{ checksum "isabelle-thys/ROOT" }}-{{ checksum isabelle-thys/Tensor_Product/Bounded_Operators/ROOT }}
-#            - v1-isabelle-heaps-2019-linux-Prerequisites-
-#      - run:
-#          name: Building QRHL Prerequisites
-#          shell: bash
-#          command: |
-#            if ! sha1sum -c ~/qrhl-prerequisites-sha1sum; then
-#              ~/install/Isabelle2019/bin/isabelle build -v -b -d ~/install/afp-2019/thys -d . QRHL-Prerequisites
-#            fi
-#            find -name 'ROOT*' | xargs sha1sum > ~/qrhl-prerequisites-sha1sum
-#            cat ~/qrhl-prerequisites-sha1sum
-#      - save_cache:
-#          paths:
-#            - ~/.isabelle
-#            - ~/qrhl-prerequisites-sha1sum
-#          key: v1-isabelle-heaps-2019-linux-Prerequisites-{{ checksum "isabelle-thys/ROOT" }}-{{ checksum "isabelle-thys/Tensor_Product/Bounded_Operators/ROOT" }}
+          key: v3-afp-2019
 
       # Build QRHL theory
       - run:
@@ -122,43 +84,48 @@ jobs:
             echo v3 > ~/isabelle-thys-checksums # Adding a tag to be able to enforce rebuilding
       - restore_cache:
           keys:
-            - v3-isabelle-heaps-2019-linux-QRHL-{{ checksum "~/isabelle-thys-checksums" }}
-            - v3-isabelle-heaps-2019-linux-QRHL-
-            - v1-isabelle-heaps-2019-linux-QRHL-
+            - v4-isabelle-heaps-2019-macos-QRHL-{{ checksum "~/isabelle-thys-checksums" }}
+            - v4-isabelle-heaps-2019-macos-QRHL-
+            - v3-isabelle-heaps-2019-macos-QRHL-
       - run:
           name: Building QRHL theories
           shell: bash
           command: |
-            ls -lhR ~/.isabelle/*/heaps # TODO remove
+            set -e
             if ! sha1sum -c ~/qrhl-sha1sum; then
-              ~/install/Isabelle2019/bin/isabelle build -v -b -d ~/install/afp-2019/thys -d . QRHL
+              case macos in
+                windows)
+                  # TODO: Under windows, need a different invocation, check whether this works
+                  ~/install/Isabelle2019.app/Isabelle/contrib/cygwin/bin/bash ~/install/Isabelle2019.app/Isabelle/bin/isabelle build -o threads=8 -v -b -d ~/install/afp-2019/thys -d . QRHL;;
+                *)
+                  ~/install/Isabelle2019.app/Isabelle/bin/isabelle build -o threads=8 -v -b -d ~/install/afp-2019/thys -d . QRHL;;
+              esac
             fi
-            ls -lhR ~/.isabelle/*/heaps # TODO remove
             sha1sum ~/isabelle-thys-checksums > ~/qrhl-sha1sum
             cat ~/qrhl-sha1sum
       - save_cache:
           paths:
             - ~/.isabelle
             - ~/qrhl-sha1sum
-          key: v3-isabelle-heaps-2019-linux-QRHL-{{ checksum "~/isabelle-thys-checksums" }}
+          key: v4-isabelle-heaps-2019-macos-QRHL-{{ checksum "~/isabelle-thys-checksums" }}
 
       # Download and cache dependencies
       - restore_cache:
           keys:
-            - v1-dependencies-linux-{{ checksum "build.sbt" }}
-            - v1-dependencies-linux-
+            - v1-dependencies-macos-{{ checksum "build.sbt" }}
+            - v1-dependencies-macos-
       - run:
           name: Downloading build dependencies (if needed)
 
           shell: bash
           command: |
-            if ! sha1sum -c ~/dependencies-sha1sum; then
+            if ! shasum -c ~/dependencies-sha1sum; then
               mkdir -p ~/install
               curl -Ls https://git.io/sbt > ~/install/sbt
               chmod +x ~/install/sbt
               ~/install/sbt update test/update </dev/null
             fi
-            sha1sum build.sbt > ~/dependencies-sha1sum
+            shasum build.sbt > ~/dependencies-sha1sum
       - save_cache:
           paths:
             - ~/install/sbt
@@ -168,13 +135,22 @@ jobs:
             - $LOCALAPPDATA\Coursier\Cache
             - ~/.cache/coursier
             - ~/dependencies-sha1sum
-          key: v1-dependencies-linux-{{ checksum "build.sbt" }}
+          key: v1-dependencies-macos-{{ checksum "build.sbt" }}
 
       - run:
           name: Running tests
           shell: bash
           command: |
-            echo "isabelle-home = $HOME/install/Isabelle2019" > qrhl-tool.conf
+            case macos in
+              windows)
+                # Isabelle process calls rebaseall and then fails, unless we deactivate it
+                > ~/install/Isabelle2019.app/Isabelle/contrib/cygwin/isabelle/rebaseall
+                ISABELLE_HOME="`cygpath -w ~/install/Isabelle2019.app/Isabelle`";;
+              linux|macos)
+                ISABELLE_HOME=~/install/Isabelle2019.app/Isabelle;;
+            esac
+
+            echo "isabelle-home = $ISABELLE_HOME" > qrhl-tool.conf
             echo "afp-root = $HOME/install/afp-2019" >> qrhl-tool.conf
 
             ~/install/sbt "testOnly -- -u scalatest-reports" </dev/null
